### ISSUE TITLE
Na liście plików w Adminie 'send to photometry'

### ISSUE THREAD

**Issue by majkelx** [wyrzykow/bhtom#144]
Na przykład dla FileID `63588`
a przetwarzanie w CCDPhot się skończyło

**Comment by arturkrawczyk** [comment]
{
        "id": 62592,
        "url": "http://ccdphot.astrolabs.pl/jobs/62592/",
        "job_id": "63588",
        "start_time": "2023-01-31T11:34:46.586854Z",
        "status_time": "2023-01-31T11:34:47.115516Z",
        "status": "R",
        "status_message": "job created",
        "progress": 2.0,
        "fits_file": "http://ccdphot.astrolabs.pl/files/fits/lsc1m004-fa03-20230130-0176-e91.fits",
        "ccdphot_result_file": null,
        "ccdphot_stdout_file": "http://ccdphot.astrolabs.pl/files/result/62592.stdout"
    },

**Comment by arturkrawczyk** [comment]
dla fileID 63586

      {
            "id": 62590,
            "url": "http://ccdphot.astrolabs.pl/jobs/62590/",
            "job_id": "63586",
            "start_time": "2023-01-31T11:32:46.749287Z",
            "status_time": "2023-01-31T11:32:47.213013Z",
            "status": "R",
            "status_message": "job created",
            "progress": 2.0,
            "fits_file": "http://ccdphot.astrolabs.pl/files/fits/lsc1m005-fa15-20230129-0268-e91.fits",
            "ccdphot_result_file": null,
            "ccdphot_stdout_file": "http://ccdphot.astrolabs.pl/files/result/62590.stdout"
        },
