### ISSUE TITLE
Repair hyperlinks in BHTOM administration for obsinfo and example fits

### ISSUE THREAD

**Issue by maja-jablonska** [wyrzykow/bhtom#148]

**Comment by arturkrawczyk** [comment]
możesz podać jakiś przykład albo opisać które pliki się nie chcą pobrać? Możliwe, że jakieś pliki zostały usunięte przeze mnie lub Tomka jak miejsce na serwerze się  skończyło a link nie został usunięty.

**Comment by majkelx** [comment]
Nie wiem czy tego nie poprawiłeś już.
