### ISSUE TITLE
Why no sky map for this event - Gaia22alz 

### ISSUE THREAD

**Issue by astromiki** [wyrzykow/bhtom#158]
<img width="1665" alt="Screenshot 2023-03-21 at 14 04 22" src="https://user-images.githubusercontent.com/19734606/226614647-dcac188f-1c25-4d2e-b10a-c68629665451.png">

**Comment by wyrzykow** [comment]
because someone created this target as a Non-Sideral (moving), instead of Sideral (not moving). Fixed now, but i could only do it at the admin level, not update.
