### ISSUE TITLE
poprawić komunikat błędu 400 żeby było jasne w czym problem

### ISSUE THREAD

**Issue by majkelx** [wyrzykow/bhtom#160]
tzn czy da się poza 400 przemycić więcej informacji

czyli podproblem sygnalizowany w BHTOM-Team/ccdphotsvc#5

**Comment by tmac-rvx** [comment]
zrobiłem kilka zmian na wszystkich nginx'ach, obserwujemy

**Comment by wyrzykow** [comment]
wyglada na to ze trzeba zamknac.
