### ISSUE TITLE
Dodanie nagłówka do plików ze ściąganą fotometrią

### ISSUE THREAD

**Issue by astromiki** [wyrzykow/bhtom#161]
Do tych plików można dodać nagłówek, w którym użytkownik dostaje info o tym co ma cytować, komu dziękować w publikacji itp.
![image](https://user-images.githubusercontent.com/19734606/227597370-67935c61-b133-44b1-966c-7152eb704da5.png)
![image](https://user-images.githubusercontent.com/19734606/227597815-cece1786-df7a-4e91-8e3a-38b8b06d4a47.png)

Przykładowa fotometria:

https://bh-tom.astrolabs.pl/bhlist/33577/

**Comment by arturkrawczyk** [comment]
nowe rzeczy dodajemy jeszcze do bhtoma czy już tylko do bhtoma2?

**Comment by astromiki** [comment]
@wyrzykow

**Comment by wyrzykow** [comment]
To mala zmiana, mozna dodac jeszcze do BH1. Ale najpierw tutaj ustalmy co tam wpiszemy.
Ja proponuje Acknowledgment.

**Comment by astromiki** [comment]
Comment: Lista papierów na stronie bhtoma + może popup przy sciaganiu danych

**Comment by astromiki** [comment]
This project used data obtained via BHTOM (https://bhtom.space), which has received funding from the European Union's Horizon 2020 research and innovation program under grant agreements No. 101004719.

**Comment by wyrzykow** [comment]
The data was obtained via BHTOM (https://bhtom.space), which has received funding from the European Union's Horizon 2020 research and innovation program under grant agreement No. 101004719 (OPTICON-RadioNet Pilot). For more information about acknowledgement and data policy please visit https://about.bhtom.space

**Comment by arturkrawczyk** [comment]
![#161](https://user-images.githubusercontent.com/13250953/228889605-3c249f2b-dac8-4401-a9f7-8a8248f5d5da.png)

**Comment by arturkrawczyk** [comment]
Może taką belkę dodać?

**Comment by astromiki** [comment]
Belka jest super, ale w plikach też powinno być.

**Comment by arturkrawczyk** [comment]
Tam jest generowany plik csv, gdzie mam taką informacje dodać?

**Comment by astromiki** [comment]
W nagłówku, każda linia powinna zaczynać się od #

**Comment by arturkrawczyk** [comment]
można testować na środowisku dev

**Comment by wyrzykow** [comment]
Dzieki @arturkrawczyk. Przetestowalem. Brakuje # przed JD (czyli wlasciwym naglowkiem). Poza tym, w belce dodaj: "By downloading the data you agree to use this acknowledgment: " i tu tekst tego co wczesniej. Po poprawce mozna wyslac na prod.

**Comment by astromiki** [comment]
Przed właściwym nagłówkiem w csv nie powinno byc "#"
