### ISSUE TITLE
Cron jobs - no success

### ISSUE THREAD

**Issue by wyrzykow** [wyrzykow/bhtom#164]
Zauwazylem, ze od dawna cron jobs nie sa "is success". Kawalek logu widoczny w admin nie pozwala zidentyfikowac ktory obiekt jest felerny:
<img width="841" alt="image" src="https://github.com/BHTOM-Team/bhtom/assets/26644157/1ff5bca1-4db9-472d-8435-883dc8bb9a62">

Ale podejrzewam, ze ktorys ma zle wspolrzedne i wyklada caly pipeline. Prosze o calego loga cron joba, moze odszyfrujemy

**Comment by tmac-rvx** [comment]
[cronjob.log](https://github.com/BHTOM-Team/bhtom/files/11611778/cronjob.log)
jest tylko to

**Comment by wyrzykow** [comment]
W logu nic nie widac nadzwyczajnego, a jednak procedura update zwraca powyzszy message bledu. Tak jakby gdzies jakies wspolrzedne byly blednie zapisane, ale nie wiem, dla ktorego targetu. Znalazlem jeden NON-SIDERAL obiekt, 
<img width="421" alt="image" src="https://github.com/BHTOM-Team/bhtom/assets/26644157/f2a8cb1a-9ac9-43a7-ae39-e27d57d2aff9">
Usuwam, zobaczymy co na to cron.

**Comment by wyrzykow** [comment]
status zielony. ZAmykam issue, ale moze wrocic.
